// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfdHOhUfWAa7D1PHRoWCAhpzyoO-Wlgns',
    appId: '1:929747306255:web:adc18c88632ba1c798e07a',
    messagingSenderId: '929747306255',
    projectId: 'todo-bbv-firebase-1539d',
    authDomain: 'todo-bbv-firebase-1539d.firebaseapp.com',
    storageBucket: 'todo-bbv-firebase-1539d.firebasestorage.app',
    measurementId: 'G-GZWKFNX2Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ZGQd8GhBaFgoPTcHUdDfb62T3Egwymc',
    appId: '1:929747306255:android:9e92e248ff95c56c98e07a',
    messagingSenderId: '929747306255',
    projectId: 'todo-bbv-firebase-1539d',
    storageBucket: 'todo-bbv-firebase-1539d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJL1c-tSGj_rSbKN3jKkIryPSEX2NmXfk',
    appId: '1:929747306255:ios:ade26d591dec186f98e07a',
    messagingSenderId: '929747306255',
    projectId: 'todo-bbv-firebase-1539d',
    storageBucket: 'todo-bbv-firebase-1539d.firebasestorage.app',
    iosBundleId: 'com.example.todoManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJL1c-tSGj_rSbKN3jKkIryPSEX2NmXfk',
    appId: '1:929747306255:ios:ade26d591dec186f98e07a',
    messagingSenderId: '929747306255',
    projectId: 'todo-bbv-firebase-1539d',
    storageBucket: 'todo-bbv-firebase-1539d.firebasestorage.app',
    iosBundleId: 'com.example.todoManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfdHOhUfWAa7D1PHRoWCAhpzyoO-Wlgns',
    appId: '1:929747306255:web:01172bafb73b229098e07a',
    messagingSenderId: '929747306255',
    projectId: 'todo-bbv-firebase-1539d',
    authDomain: 'todo-bbv-firebase-1539d.firebaseapp.com',
    storageBucket: 'todo-bbv-firebase-1539d.firebasestorage.app',
    measurementId: 'G-S85YZ7H3NZ',
  );
}
